#!/usr/bin/env python2

from __future__ import print_function
from apiclient.discovery import build
from httplib2 import Http
from oauth2client import file, client, tools
import json
import os
import click
from os import listdir
from os.path import isfile, join
from utils import readjson
import requests


def aggregate(data):
    agg = data['title']
    if not agg:
        raise RuntimeError('Missing title')
    if 'description' in data and data['description']:
        agg = agg+'\n\n'+data['description']
    if 'comments' in data:
        agg += '\n\nKommentarer\n'
        for comment in data['comments']:
            agg += comment['authorname']+': '+comment['text']+'\n'
    if len(agg) > 950:
        raise RuntimeError('Aggregated description too long: '+agg)
    return agg


def is_photo_json(folder, f):
    return isfile(join(folder, f)) and f.endswith('.json') and f != 'meta.json'


def full_prefix(folder, f):
    return os.path.join(folder, f[:-5])


def upload(folder):
    meta = readjson(os.path.join(folder, 'meta.json'))

    # Setup the Photo v1 API
    SCOPES = 'https://www.googleapis.com/auth/photoslibrary'
    store = file.Storage('credentials.json')
    creds = store.get()
    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets('client_secret.json', SCOPES)
        creds = tools.run_flow(flow, store)
    service = build('photoslibrary', 'v1', http=creds.authorize(Http()))
    access_token = service._http.request.credentials.access_token

    print(meta['title'])

    files = [full_prefix(folder, f) for f in listdir(folder)
             if is_photo_json(folder, f)]
    files.sort()

    result = service.albums().create(body={
        'album': {'title': meta['title']}
    }).execute()
    aid = result['id']

    def upload(service, file):
        f = open(file, 'rb').read()

        url = 'https://photoslibrary.googleapis.com/v1/uploads'
        headers = {
            'Authorization': "Bearer " + access_token,
            'Content-Type': 'application/octet-stream',
            'X-Goog-Upload-File-Name': file,
            'X-Goog-Upload-Protocol': "raw",
        }

        r = requests.post(url, data=f, headers=headers)
        print('Uploaded '+file)
        return r.content

    for filename in files:
        info = readjson(filename+'.json')
        jpg = filename+'.jpg'
        description = aggregate(info)
        token = upload(service, jpg)
        print('TOKEN '+token)

        url = 'https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate'
        headers = {
            'Authorization': "Bearer " + access_token,
            'Content-Type': 'application/json'
        }
        req = {
            'albumId': aid,
            'newMediaItems': [
                {
                    'description': description,
                    'simpleMediaItem': {
                        'uploadToken': token
                    }
                }
            ],
            'albumPosition': {
                'position': 'LAST_IN_ALBUM'
            }
        }
        r = requests.post(url, data=json.dumps(req), headers=headers)
        print('REQUEST')
        print(json.dumps(req))
        print('RESPONSE CONTENT')
        print(r.content)


@click.command()
@click.option(
    '--folder',
    required=True,
    help='the folder containing meta.json and the photos')
def to_google(folder):
    upload(folder)


if __name__ == '__main__':
    to_google()
